"""new tables

Revision ID: 831ae05d7ee0
Revises: 
Create Date: 2023-06-10 12:31:01.648158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831ae05d7ee0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
